<?php

include("header.php");//NAVBAR

?>
	<section class="MVIEW row justify-content-center paddingBotom">
				<div class="col-lg-10">
					<div class="row justify-content-center">
                        <h1 class="text-center mt-5 mb-5">Conditions Génerales d'Utilisations - (CGU)</h1>

                        <p>
                            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, nostrum non! Velit mollitia vel ratione nulla, modi adipisci ipsum similique dicta veritatis incidunt accusamus sed aspernatur. Rerum corrupti consequatur necessitatibus?</span>
                            <span>Illum dicta rem obcaecati laboriosam, magni numquam sed dolores excepturi neque sint molestiae saepe modi fugiat vero? Sapiente deserunt, dolorum eos velit natus culpa ipsum, qui laboriosam, quos omnis explicabo.</span>
                            <span>Impedit ipsum possimus error! Sunt reiciendis ipsum fugit recusandae ea fuga veritatis corporis odit illo non optio, veniam totam dolorem dignissimos doloremque tempore facilis dolore quos earum quas odio. Fuga?</span>
                            <span>Est neque necessitatibus officia facere eum recusandae, odit porro dolor! Nisi, illum assumenda eligendi quo, accusamus, eos consequuntur incidunt velit ipsum dolore ipsam ullam soluta! Molestiae neque recusandae error mollitia.</span>
                            <span>Placeat alias voluptatum voluptate ipsam natus inventore at quasi? Explicabo aliquam minus facilis corporis temporibus dolorem reiciendis dolor ipsam, dignissimos voluptatem, rem ullam ipsum excepturi consectetur unde labore quisquam vero.</span>
                            <span>Maiores incidunt consequuntur dolore corporis a. Quidem saepe eligendi totam praesentium tempore nemo. Nemo provident ratione architecto ullam veniam dolorem animi, aperiam, odit tempora exercitationem error recusandae quae mollitia ipsam.</span>
                            <span>Voluptas commodi iusto sunt harum totam reiciendis nemo, nulla ipsam nesciunt fuga consectetur, nisi inventore possimus enim! Asperiores molestiae nihil atque ad omnis aliquam provident minus distinctio, incidunt laudantium sit.</span>
                            <span>In vero magni fugit, quod cumque omnis dolorum neque magnam modi quis blanditiis sit temporibus minima molestias, harum ullam nisi fuga autem tenetur ab eos? Voluptate, facilis? Porro, vel sunt.</span>
                            <span>Dolore earum magni expedita voluptates asperiores est nihil, maiores obcaecati, non ea deserunt nesciunt quibusdam aperiam, quis perspiciatis architecto facilis repudiandae culpa consectetur voluptatibus modi magnam corrupti. Sunt, ipsa autem?</span>
                            <span>Quae libero autem nemo nisi itaque mollitia temporibus voluptates sed minus praesentium? Sint, fuga atque. Veritatis aut, ipsam soluta suscipit illum ipsa laboriosam quod excepturi eius, necessitatibus vero, consequatur provident.</span>
                            <span>Maxime rem, quibusdam iste atque numquam error culpa praesentium, quo reprehenderit nobis quas officia quae et! Magnam voluptatibus doloribus pariatur voluptates, nisi velit, esse natus aperiam ad odit quasi adipisci?</span>
                            <span>Aspernatur tenetur omnis neque sequi eaque quidem, ea inventore, ducimus facere ut dolorum, ipsa aut ratione consectetur labore. Est nobis doloribus porro. Mollitia minus iste numquam earum! Suscipit, alias amet.</span>
                            <span>Voluptatum, nemo explicabo. Dicta repellendus repellat totam, excepturi voluptatum cupiditate atque, delectus nulla deserunt sapiente maiores suscipit. Quod voluptate eligendi hic laboriosam? Quam optio recusandae sapiente! Ad itaque doloremque fuga!</span>
                            <span>Amet nihil porro sapiente. Expedita numquam soluta fugit, fuga quibusdam temporibus. Neque praesentium suscipit sint laboriosam excepturi beatae consequuntur cupiditate, quidem magnam veritatis vero provident numquam, atque iste labore velit.</span>
                            <span>Cumque explicabo possimus quas accusantium dolore, in iste deleniti illo inventore dolor optio voluptatibus quasi eveniet sint earum totam libero neque deserunt fuga eos aut ad! Sit corrupti eligendi ad.</span>
                            <span>Amet unde sint neque quia, vitae soluta vero eligendi! Eligendi in minus natus facere quia? Cumque repellat corporis molestias voluptate aliquid, provident officiis odio odit nostrum quis iusto earum aperiam!</span>
                            <span>Voluptatem molestias aliquid alias adipisci accusantium temporibus, quos eligendi facere dignissimos voluptate explicabo numquam sapiente eius facilis aut iusto libero quaerat aperiam optio maiores qui repellendus. Quam inventore fugiat similique.</span>
                            <span>Illo reiciendis ab, magni minima odio molestias quod cum, exercitationem ut perspiciatis recusandae, veritatis perferendis quam placeat quae sequi distinctio explicabo tempore voluptate eum quisquam illum repellendus molestiae. Vel, iure.</span>
                            <span>Quis architecto veniam aspernatur magni odio harum tempora sint cum, possimus vero aliquam dolorum omnis, porro perferendis ducimus minima eligendi sed dolore quibusdam. Omnis odit dolore repellendus in, veritatis ea!</span>
                            <span>Molestiae est hic, exercitationem ut repudiandae atque! Tenetur nemo molestiae, doloribus, velit hic porro voluptatum iure magnam recusandae suscipit, eum et aliquid commodi delectus repudiandae non adipisci voluptas omnis rerum.</span>
                            <span>Temporibus quidem accusantium adipisci consequuntur nam, rerum voluptatibus maiores eveniet veritatis deleniti. Facilis natus hic quisquam nam aliquam non dolore ad corporis veritatis ipsam distinctio delectus, eligendi eos voluptas ipsum?</span>
                            <span>Veritatis, facere nobis nesciunt doloribus, aspernatur at incidunt reiciendis eveniet praesentium quas repellendus asperiores quisquam hic inventore atque harum aut soluta in voluptatum fuga sit? Aliquid rem quaerat nostrum praesentium.</span>
                            <span>Ut mollitia ea delectus magnam ab? Culpa vitae, adipisci exercitationem quo delectus dicta magnam doloremque? Architecto reiciendis repellendus, ex, vitae, possimus voluptatibus labore laboriosam provident natus earum iusto culpa minus.</span>
                            <span>Voluptatum optio voluptates placeat laudantium deserunt harum amet in quas. Nostrum molestiae officiis eos expedita aliquam corrupti ad aspernatur quibusdam dolore quis sapiente, accusamus exercitationem rem, magnam, eveniet itaque ipsa.</span>
                            <span>Ipsa, aliquam? Labore quia fuga eius, assumenda sunt iusto deleniti blanditiis totam debitis possimus nesciunt ullam eos nemo reprehenderit ab dicta ipsa facere sequi est vel maiores. Pariatur, doloremque vitae!</span>
                            <span>Suscipit cumque unde, dolore repudiandae libero quam quas, veritatis mollitia reiciendis aperiam recusandae aspernatur! Magni quos labore veniam maiores? Odit, omnis ex laudantium minus quis quod assumenda itaque adipisci iste?</span>
                            <span>Cupiditate ex, repellat officia hic sapiente doloribus atque nobis id, rerum ipsa expedita, autem odit? Est aperiam, ad facilis illo consequuntur accusantium dolorem perspiciatis. Consectetur quaerat quasi dolorem odio ea!</span>
                            <span>Expedita exercitationem quis ab mollitia, culpa animi a nobis veritatis velit et unde sit neque molestias, asperiores ullam laborum, architecto dolorem aliquam assumenda voluptates quisquam autem labore provident ea. Laboriosam?</span>
                            <span>Praesentium doloremque quas dicta facilis soluta magni officia tenetur provident dolor repellat nihil, aspernatur, recusandae dolore architecto numquam vero quam! Voluptatum, fugit. Illum libero nulla iusto eveniet alias corrupti exercitationem!</span>
                            <span>Consequuntur dignissimos corporis error expedita molestiae sequi quod voluptatibus soluta enim iure consequatur perferendis dolore voluptates blanditiis officiis numquam voluptas, aliquid cum fuga minima nostrum! Tenetur vero expedita omnis recusandae.</span>
                            <span>Facilis, quas. Magnam excepturi eum et ut dolorum mollitia quae ab totam quod fugiat possimus corporis asperiores dolores eos distinctio sed enim quia tempore esse, ipsam officiis odit. Commodi, omnis.</span>
                            <span>Culpa deleniti impedit repellat officiis illum vel, eos, blanditiis nihil quas, tempore perferendis itaque esse nulla mollitia nobis provident voluptate quis. Sapiente, iusto possimus. Ad aspernatur neque voluptate nobis velit!</span>
                            <span>Ex vitae hic earum repellat ullam eos magni enim reiciendis perspiciatis esse numquam commodi, soluta deserunt nemo illo? Necessitatibus quos in enim nisi. Doloribus fugit porro modi provident quasi officiis!</span>
                            <span>Explicabo a facere ullam itaque ab autem error quae dolorum dolor sequi numquam officiis perferendis quia molestiae, odio nulla incidunt facilis, repellat id alias? Autem sit iste laudantium consectetur eligendi.</span>
                            <span>Mollitia repellendus distinctio placeat nulla soluta nobis corporis minima eum at nesciunt sint, dicta ipsam tenetur excepturi, quos nihil. Nostrum quam, nisi illum aliquid pariatur hic ea veniam repellat error?</span>
                            <span>Exercitationem tempora eum ratione deleniti rem laboriosam, expedita ex facere eligendi, vitae nulla? Natus est debitis ipsum excepturi illo velit, quibusdam, quam neque esse in ea omnis nostrum minus obcaecati!</span>
                            <span>Velit, esse voluptate? Nulla, exercitationem facilis atque quae odio itaque dolores numquam, est laborum nostrum sint ut ipsam incidunt dignissimos cupiditate placeat! Delectus consequuntur laudantium impedit, quis magnam unde hic.</span>
                            <span>Sed placeat laborum a illo? Obcaecati iusto, quos aspernatur error iste sequi magnam ex ea corrupti reiciendis voluptate ullam ad dolore quam accusantium ab libero in ut? Saepe, quas temporibus.</span>
                            <span>Quisquam quis laboriosam odit quas possimus fugit reiciendis aliquid dolor eaque repudiandae inventore veniam tempora asperiores modi consequatur, distinctio enim quasi expedita natus recusandae! Vitae eos impedit velit! Harum, mollitia.</span>
                            <span>Hic nihil blanditiis dolores, cupiditahttp://localhost/siteCssPhp/filRouge/index.phppernatur, necessitatibus vero asperiores provident culpa at obcaecati excepturi rem repudiandae assumenda. Blanditiis earum, alias excepturi, ullam explicabo dolores, ea dolorum veritatis nisi labore praesentium.</span>
                            <span>Qui magnam cum aspernatur a quaerat facilis tenetur harum distinctio, ipsa dolores? Unde eaque nemo ducimus, culpa magnam fugit, facere, a omnis magni officiis maxime itaque excepturi mollitia? Porro, illum?</span>
                            <span>Perspiciatis tempora nobis totam, praesentium vitae deserunt voluptate recusandae modi possimus asperiores nemo voluptates ab, tempore aliquid ipsa exercitationem aliquam quod, error beatae. Debitis, accusamus omnis perspiciatis ad iste cumque!</span>
                            <span>Nobis at ratione sequi ea accusantium, labore vero magni, perspiciatis voluptatum quas earum quidem distinctio magnam perferendis ut ab? Nesciunt reprehenderit quasi quis nemo similique sequi illum in quas voluptate.</span>
                            <span>Modi, similique placeat sequi minima odit sed. Architecto exercitationem a amet eum, accusamus ex nemo atque aperiam quisquam impedit soluta repellat voluptate delectus quia laudantium assumenda facilis. Laudantium, doloribus magnam!</span>
                            <span>Quod adipisci cumque esse pariatur quae. Porro dolore illum eum odit beatae ab, at ratione saepe, incidunt, libero soluta adipisci explicabo numquam vitae aut id cupiditate voluptatum fuga aperiam. Rerum.</span>
                            <span>Voluptatibus ea nam esse error, quidem vel accusantium aspernatur natus adipisci totam sint voluptates, impedit dolorum labore consectetur consequuntur velit culpa delectus! Saepe itaque, similique laborum nihil maxime iste. Accusantium.</span>
                            <span>Sint repellendus quod cupiditate laboriosam nulla sunt eligendi dignissimos delectus expedita ullam obcaecati sapiente eius earum dicta quas, eveniet adipisci deleniti amet magni nam, qui soluta rem facilis sed? Aliquam?</span>
                        </p>
                        <p>
                            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus, tempora nemo est quos aliquam, ad velit amet in ratione quisquam quidem natus modi quod animi assumenda repellat ex nesciunt quis.</span>
                            <span>Alias assumenda recusandae qui voluptas ullam expedita vitae hic ipsam consectetur necessitatibus? Tempora obcaecati, temporibus assumenda maiores consequatur deleniti ab in laudantium sapiente saepe cumque odit dolorum velit. Quam, nobis!</span>
                            <span>Magnam voluptatum, aliquid explicabo commodi quos fugiat labore fugit. Hic minima, sed aut quaerat quibusdam optio? Cumque, autem. Corporis, maxime amet. Eum consequuntur amet ut commodi ipsum ratione sed quaerat!</span>
                            <span>Obcaecati unde aspernatur cum? Placeat exercitationem ab illo maxime iusto mollitia odio tenetur autem earum incidunt. Atque quae odit beatae est repellendus ex sed fugiat totam nemo, deleniti harum sint?</span>
                            <span>Earum perferendis magni excepturi laudantium pariatur aspernatur animi optio facilis mollitia atque blanditiis enim quasi a vero temporibus alias vitae itaque tenetur ratione possimus illo natus, error fugit? Laborum, illo.</span>
                            <span>Itaque, quis. Et modi laborum magnam nostrum consequuntur! Officia minima, repudiandae nostrum saepe cumque ratione rem labore beatae! Beatae dolore voluptatibus minus quisquam, saepe pariatur repellendus tenetur nam doloribus harum.</span>
                            <span>Voluptate quas error id similique. Magni harum provident cumque exercitationem cupiditate, unde veritatis sint! Deserunt saepe molestias adipisci? Ipsum quas dolorum quod tempore porro laborum fuga blanditiis, doloremque sed eos!</span>
                            <span>Ducimus dolore blanditiis cum beatae incidunt excepturi nobis vero quaerat nulla natus iusto accusantium nam nisi saepe voluptatibus laborum, odio expedita! Praesentium placeat voluptate necessitatibus consequuntur rerum dolores temporibus at.</span>
                            <span>Dignissimos ratione laborum facilis beatae doloribus repellendus aut rem nobis accusamus voluptatem. Labore nobis, ipsum nam voluptate soluta corporis numquam quasi sit cupiditate voluptates ipsam. Cupiditate ipsum voluptas mollitia dignissimos.</span>
                            <span>Facilis assumenda quidem ratione totam eligendi non, impedit voluptatum consequuntur iste id aliquid voluptas quisquam natus tempore magni officiis libero. Voluptates minus, natus impedit autem neque ipsam voluptatibus aut explicabo.</span>
                        </p>
                        <p>
                            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti vero nulla iusto eveniet expedita libero officia eum nesciunt obcaecati minus commodi doloremque fugiat velit qui soluta, illum modi ea dolorem!</span>
                            <span>Iure sint libero non repudiandae ullam ea esse harum tempora saepe sunt nemo fugit fuga magnam alias, voluptatibus natus voluptas odio ipsa similique perferendis quibusdam praesentium obcaecati. Numquam, distinctio magni!</span>
                            <span>Corrupti, nostrum consectetur. Explicabo, exercitationem ab iusto totam ut aliquam architecto voluptate maiores quasi suscipit dolorum similique et. Tenetur, sapiente impedit repellat suscipit ipsa sed maiores minus at pariatur hic!</span>
                            <span>Facere neque dignissimos veritatis libero, qui delectus optio accusamus ratione officiis excepturi magni labore veniam corporis. Quisquam, libero quam. Dolor facere exercitationem eius ea voluptates sunt deleniti officia aspernatur inventore?</span>
                            <span>Voluptatum ut eveniet nemo! Dolorem deserunt fugiat porro iste labore nihil aliquid nostrum sapiente rem, tempore facilis quidem ducimus natus at vero minus. Numquam fugit deserunt est sapiente! Accusantium, laboriosam?</span>
                            <span>Dolore alias sapiente a officiis reprehenderit eius suscipit natus ea dolores. Odit distinctio laboriosam nisi in alias dolorem officiis, eius dolor nostrum. Illum ab dolores aspernatur rem provident quaerat quis.</span>
                            <span>Dignissimos minus nostrum dolore accusamus enim? Porro id facilis dolore voluptatem in nesciunt vero eius at voluptatibus. Libero doloremque rerum atque suscipit saepe rem recusandae earum exercitationem dolorem impedit! Laudantium?</span>
                            <span>Dignissimos, molestias odio, ad quos aspernatur itaque velit modi ipsam quae aliquam excepturi necessitatibus sequi. Reprehenderit, hic voluptatibus fuga voluptatum iusto quisquam possimus soluta. Explicabo omnis sint modi. Cupiditate, corrupti!</span>
                            <span>Laboriosam a necessitatibus velit explicabo fugit. Laborum adipisci officiis fugit necessitatibus vitae eius, hic quo voluptates labore deleniti alias recusandae nam ut exercitationem deserunt sapiente molestias quibusdam harum esse rem?</span>
                            <span>Inventore repellendus veritatis optio modi vitae facilis, provident deleniti earum. Sunt quasi minus magnam, voluptate beatae cumque quibusdam aspernatur maxime a libero, iusto voluptatum iure. Modi, numquam. Consectetur, magni esse.</span>
                            <span>Enim, temporibus rem molestiae beatae expedita asperiores debitis animi officiis illum quisquam provident itaque nostrum necessitatibus? Deserunt amet nihil aut culpa magni dolor distinctio, perspiciatis, porro sequi voluptates, quidem dolorem?</span>
                            <span>Omnis voluptates ipsa quia distinctio id libero praesentium. Quam facere iure est voluptates minus repellendus rem ipsum odio soluta fuga consequatur sequi error tenetur, illum dolore, quidem expedita nisi? Architecto?</span>
                            <span>Aliquam sapiente, quidem alias reprehenderit iure molestias, labore consectetur eveniet repellendus ullam debitis nulla soluta expedita numquam veniam tempore enim unde dolore consequatur minus, odit placeat? Nobis iure quaerat dolorem?</span>
                            <span>Eligendi ab, natus voluptas ex ducimus ipsum sit rem dolores distinctio ut debitis dolorem earum placeat quidem ratione molestias eos aliquid cumque autem magni quo voluptatibus, eius fugit amet. Temporibus.</span>
                            <span>Quidem, quia commodi libero odio culpa optio quae molestiae quisquam at quis sunt ipsa velit, qui ab ullam repellat neque, a labore nihil eveniet vel quam ipsum? Id, earum ab.</span>
                        </p>

                    </div>
                </div>
    </section>
    
    <?php

include("footer.php");

?>